### ISSUE TITLE
Monocle Compatibility

### ISSUE THREAD

**Issue by jasonmli** [bioinfo-ibms-pumc/SCSA#24]
Hi, I generated some cell clusters using Monocle that noted their gene expression based on this csv file:
[Infected_cell_makeup.csv](https://github.com/bioinfo-ibms-pumc/SCSA/files/8455712/Infected_cell_makeup.csv)

Would it be possible to convert this format to be utilized by SCSA for cell type identification?

Thanks!

**Comment by bioinfo-ibms-pumc** [comment]
Sorry for late. You can convert it manually to other format. Maybe in the late version I'll finish the request.
