### ISSUE TITLE
Request an update of whole.db

### ISSUE THREAD

**Issue by myshu2017-03-14** [bioinfo-ibms-pumc/SCSA#28]
Hi,
  CellMarker database has been updated to version 2.0 recently.（http://bio-bigdata.hrbmu.edu.cn/CellMarker ） I hope you can update it synchronously.

Best wishes,

Myshu

**Comment by Starlitnightly** [comment]
Hi @myshu2017-03-14 

I recently encountered the same issue with the update of whole.db in SCSA package. After working on a solution, I developed a new package called `Pyomic` which solves this problem.  The tutorial of pySCSA can be found at [here](https://pyomic.readthedocs.io/en/latest/Tutorials-single/t_cellanno/). 

In Pyomic:
- Updated the database of SCSA from [CellMarker2.0](http://bio-bigdata.hrbmu.edu.cn/CellMarker/)
- Fix the error database key `Ensembl_HGNC` and `Ensembl_Mouse` of SCSA 

Pyomic is now available and I invite you to try it out and provide feedback. You can find more information and installation instructions on [Pyomic](https://github.com/Starlitnightly/Pyomic). I hope this will be helpful for anyone who has faced similar issues with SCSA. Let me know if you have any questions or feedback. Thanks!"

**Comment by bioinfo-ibms-pumc** [comment]
Thans for all your suggestions. I'm sorry for late because of other things. The database was updated and  CellMarker v2 was intergrated. Users can use it with the cmd ' -d whold_v2.db' instead. Thanks again.

**Comment by myshu2017-03-14** [comment]
> Thans for all your suggestions. I'm sorry for late because of other things. The database was updated and CellMarker v2 was intergrated. Users can use it with the cmd ' -d whold_v2.db' instead. Thanks again.

Hi @bioinfo-ibms-pumc ,
 I recently tested the v2 version of the `whole_v2.db` and got errors as follow:
![image](https://user-images.githubusercontent.com/26398036/231629638-7ae95cff-f358-45cb-bdd8-cbaf5385b1a2.png)

And I also tested the old version  only `-d` parameter was changed, and it ran without errors. Could you help me see how to solve the errors of the new version?

Best wishes,

Myshu

**Comment by Starlitnightly** [comment]
> > Thans for all your suggestions. I'm sorry for late because of other things. The database was updated and CellMarker v2 was intergrated. Users can use it with the cmd ' -d whold_v2.db' instead. Thanks again.
> 
> Hi @bioinfo-ibms-pumc , I recently tested the v2 version of the `whole_v2.db` and got errors as follow: ![image](https://user-images.githubusercontent.com/26398036/231629638-7ae95cff-f358-45cb-bdd8-cbaf5385b1a2.png)
> 
> And I also tested the old version only `-d` parameter was changed, and it ran without errors. Could you help me see how to solve the errors of the new version?
> 
> Best wishes,
> 
> Myshu

Hi, 

I think you need to change the version of Pandas to `1.5.3` to solve. As a general rule, you need to ensure that the pandas version of the build db file is the same as the author for it to work properly.

**Comment by myshu2017-03-14** [comment]
> > > Thans for all your suggestions. I'm sorry for late because of other things. The database was updated and CellMarker v2 was intergrated. Users can use it with the cmd ' -d whold_v2.db' instead. Thanks again.
> > 
> > 
> > Hi @bioinfo-ibms-pumc , I recently tested the v2 version of the `whole_v2.db` and got errors as follow: ![image](https://user-images.githubusercontent.com/26398036/231629638-7ae95cff-f358-45cb-bdd8-cbaf5385b1a2.png)
> > And I also tested the old version only `-d` parameter was changed, and it ran without errors. Could you help me see how to solve the errors of the new version?
> > Best wishes,
> > Myshu
> 
> Hi,
> 
> I think you need to change the version of Pandas to `1.5.3` to solve. As a general rule, you need to ensure that the pandas version of the build db file is the same as the author for it to work properly.


Yes！ I updated the version of pandas and it worked
