### ISSUE TITLE
Zero marker sets found -- error

### ISSUE THREAD

**Issue by jhb1980** [bioinfo-ibms-pumc/SCSA#3]
Hi! I have tried SCSA on a Seurat 'FindAllMarkers' output from a public PBMC dataset. SCSA starts well into Cluster 0 (-> Monocytes), but crashes out on Cluster 1. Attaching the culprit csv
[seurat-markers.csv.zip](https://github.com/bioinfo-ibms-pumc/SCSA/files/4561650/seurat-markers.csv.zip)

Command line:
`SCSA.py -d /Users/Husband/SCSA/whole.db -s seurat -i SCT-20_seu-markers.csv -o SCT-20_seu-annotation -k All -E -g Human -p 0.01 -f 1.5`

Error output and stop at Cluster 1 >>>

############################## Cluster 1 ##############################

!WARNING3:Zero marker sets found, type:marker
!WARNING3:Change the threshold or tissue name and try again?
!WARNING3:EnsemblID or GeneID,try '-E' command?
Traceback (most recent call last):
  File "/Users/Husband/SCSA/SCSA.py", line 1111, in <module>
    p.run_cmd(args)
  File "/Users/Husband/SCSA/SCSA.py", line 1077, in run_cmd
    outs = anno.run_detail_cmd()
  File "/Users/Husband/SCSA/SCSA.py", line 1012, in run_detail_cmd
    outs = self.calcu_seurat_group(self.args.input,self.args.Gensymbol)
  File "/Users/Husband/SCSA/SCSA.py", line 428, in calcu_seurat_group
    h_values,colnames = self.get_cell_matrix(newexps,ltitle,fid,gcol,ccol,abs_tag)
  File "/Users/Husband/SCSA/SCSA.py", line 836, in get_cell_matrix
    return DataFrame(),set(colnames)
TypeError: 'NoneType' object is not iterable

**Comment by bioinfo-ibms-pumc** [comment]
Sorry for the inconvenience. I have just fix the error. In addition, thereseems to be no significant marker gene in the cluster 1 under the certain filter. You may change the -f command or reanalysis from seurat.
