### ISSUE TITLE
May I select multiple tissues at the same time

### ISSUE THREAD

**Issue by listen2099** [bioinfo-ibms-pumc/SCSA#6]
Hi author, I've been testing the software recently and I've found that the annotation results are very good. 

But I wondered if it was possible to specify multiple tissue types when using cellmarker database by -k parameter, and how?

Thanks!

**Comment by bioinfo-ibms-pumc** [comment]
Thanks. In this version, SCSA can't select multiple tissues and I'll add this function in the near future. Thank you for your suggestion.

**Comment by listen2099** [comment]
Great!  Thank you!

**Comment by bioinfo-ibms-pumc** [comment]
I just add the multiple choice for "-k". Please update SCSA and see whether it could be run normally. But I don't think multiple tissues could give a better result unless your experiment was designed specially for multiple tissues.

**Comment by listen2099** [comment]
Hi author, I'm very excited to see this feature. In many cases, the situation of the samples in the experiment is very complicated, so this feature will be of great help to researchers. Thank you again for your contribution!
